#include "_prog_conventions.h"
#define CNTRL_GRP_0 		3
#define PA_GRP_0		0
#define PB_GRP_0		1
#define PC_GRP_0		2
#define CNTRL_GRP_1		7
#define PA_GRP_1		4
#define PB_GRP_1		5
#define PC_GRP_1		6
#define CNTRL_GRP_2             11
#define PA_GRP_2                8 
#define PB_GRP_2                9
#define PC_GRP_2                10
#define CNTRL_GRP_3             15
#define PA_GRP_3                12 
#define PB_GRP_3                13 
#define PC_GRP_3                14
#define CNTRL_GRP_4             19
#define PA_GRP_4                16
#define PB_GRP_4                17
#define PC_GRP_4                18
